trailheadapps/visualforce-to-lwc

force-app/main/default/lwc/errorPopover/errorPopover.html
SLDS classes for popover component were not working
No logged issue
[X ] Code linting and formatting was performed.
=> Fix SLDS classes for popover component

force-app/main/default/lwc/apexUtils/__tests__/apexUtils.test.js, force-app/main/default/lwc/apexUtils/__tests__/data/soqlData.json, jest.config.js
Add tests for apexUtils module
Add unit tests for apexUtils module
[ x] Tests for the proposed changes have been added/updated.
[ x] Code linting and formatting was performed.
Module had no tests
Module has tests
=> Add jest config file and tests for apexUtils

force-app/main/default/lwc/basicListGetListUi/__mocks__/basicListGetListUi.html, force-app/main/default/lwc/basicListGetListUi/__mocks__/basicListGetListUi.js, force-app/main/default/lwc/basicListGetListUiWrapper/__tests__/basicListGetListUiWrapper.tests.js, force-app/main/default/lwc/basicListGetListUiWrapper/basicListGetListUiWrapper.js
Adds tests for  basicListGetListUiWrapper
[ x] Tests for the proposed changes have been added/updated.
[ x] Code linting and formatting was performed.
basicListGetListUiWrapper had no tests
basicListGetListUiWrapper has tests
=> Tests for  basicListGetListUiWrapper

force-app/main/default/lwc/createMixedRecordsApexWrapper/__tests__/createMixedRecordsApexWrapper.test.js, force-app/main/default/lwc/createMixedRecordsApexWrapper/createMixedRecordsApexWrapper.html, force-app/main/default/lwc/createMixedRecordsWireFunctionsWrapper/createMixedRecordsWireFunctionsWrapper.html
Add tests for CreateMixedRecordsApexWrapper
[x ] Tests for the proposed changes have been added/updated.
[x ] Code linting and formatting was performed.
CreateMixedRecordsApexWrapper didn't have tests
CreateMixedRecordsApexWrapper has tests
=> Tests for CreateMixedRecordsApexWrapper

force-app/main/default/lwc/editableList/__mocks__/editableList.js, force-app/main/default/lwc/editableListWrapper/__tests__/editableListWrapper.test.js
Adds tests for editableListWrapper
editableListWrapper didn't have tests
editableListWrapper has tests
=> Tests for editableListWrapper

force-app/main/default/lwc/editRecord/__tests__/editRecord.test.js, force-app/test/jest-mocks/lightning/platformShowToastEvent.js, force-app/test/jest-mocks/schema.js, jest.config.js
Adds tests for editRecord
editRecord didn't have tests
editRecord didn't has tests
=> Tests for editRecord

force-app/main/default/lwc/datatableWithCustomTypes/__tests__/datatableWithCustomTypes.test.js
Adds tests for DatatableWithCustomTypes
DatatableWithCustomTypes didn't have tests
DatatableWithCustomTypes has tests
=> Tests for DatatableWithCustomTypes

force-app/main/default/lwc/editRecordWrapper/__tests__/editRecordWrapper.test.js
Adds tests for editRecordWrapper
editRecordWrapper didn't have tests
editRecordWrapper has tests
=> Tests for editRecordWrapper

force-app/main/default/lwc/.eslintrc.json, force-app/main/default/lwc/basicListGetListUi/__tests__/basicListGetListUi.test.js, force-app/main/default/lwc/basicListGetListUi/__tests__/data/formatGetListUiSObjects.json, force-app/main/default/lwc/basicListGetListUi/__tests__/data/getListUi.json, force-app/main/default/lwc/ldsUtils/__mocks__/ldsUtils.js
Adds tests for basicListGetListUi
basicListGetListUi didn't have tests
basicListGetListUi has tests
=> Tests for basicListGetListUi

force-app/main/default/lwc/basicListGetListUiWrapper/__tests__/basicListGetListUiWrapper.test.js, force-app/main/default/lwc/createMixedRecordsApexWrapper/__tests__/createMixedRecordsApexWrapper.test.js, force-app/main/default/lwc/createMixedRecordsWireFunctionsWrapper/__tests__/createMixedRecordsWireFunctionsWrapper.test.js, force-app/main/default/lwc/editRecordWrapper/__tests__/editRecordWrapper.test.js, force-app/main/default/lwc/editableListWrapper/__tests__/editableListWrapper.test.js, force-app/main/default/lwc/pageMessagesForm/__tests__/pageMessagesForm.test.js
Rename elements variables and file names for consistency
Some elements variables ended in 'Cmp' instead of 'El'
Some test files where named in plural (with 'tests')
All elements variables end in 'El'
All test files where named in singular (with 'test')
=> Rename elements variables and file names for consistency

force-app/main/default/lwc/panelGridWrapper/__tests__/panelGridWrapper.test.js
add jest tests for panelGridWrapper lwc
=> add jest tests for panelGridWrapper lwc

force-app/main/default/lwc/panelBarWrapper/__tests__/panelBarWrapper.test.js
tests for c-panel-bar-wrapper lwc component
=> tests for c-panel-bar-wrapper lwc component

force-app/main/default/lwc/listInfiniteScrollingWrapper/__tests__/listInfiniteScrollingWrapper.test.js, force-app/main/default/lwc/listInfiniteScrollingWrapper/listInfiniteScrollingWrapper.js
This PR added a test for listInfiniteScrollingWrapper.js and updates listInfiniteScrollingWrapper.js to export the right class name.
N/A
There was no test, and the JS called to the wrong class name
Now there is a test, and the JS is fixed.
=> Add test for list infinite scrolling wrapper

force-app/main/default/lwc/errorPopover/__tests__/errorPopover.test.js
test for errorPopover lwc component
=> test for errorPopover lwc component

force-app/main/default/lwc/exampleWrapper/__tests__/exampleWrapper.test.js
test for exampleWrapper lwc component
=> test for exampleWrapper lwc component

force-app/main/default/lwc/lightningActionLwc/__tests__/lightningActionLwc.test.js
Adds a test for the component lightningActionLwc
N/A - Part of the test coverage effort
lightningActionLwc had no tests
lightningActionLwc has tests!
=> Add test for lightningActionLwc

force-app/main/default/lwc/listInfiniteScrollingGetListUiWrapper/__tests__/listInfiniteScrollingGetListUiWrapper.test.js
Adds a test for listInfiniteScrollingGetListUiWrapper
N/A
No tests for the component listInfiniteScrollingGetListUiWrapper
Added tests for the component listInfiniteScrollingGetListUiWrapper
=> Add test for list infinite scrolling get list ui wrapper

force-app/main/default/lwc/listInfiniteScrollingGetListUi/__tests__/data/mockGetAccountData.json, force-app/main/default/lwc/listInfiniteScrollingGetListUi/__tests__/listInfiniteScrollingGetListUi.test.js, force-app/main/default/lwc/listInfiniteScrollingGetListUi/listInfiniteScrollingGetListUi.js
Adds tests for listInifiniteScrollingGetListUi and updates listInifiniteScrollingGetListUi.js for readability
N/A
No tests for listInifiniteScrollingGetListUi and fuction in listInifiniteScrollingGetListUi.js needed formating for readability
Tests for listInifiniteScrollingGetListUi added and updates listInifiniteScrollingGetListUi.js for readability
=> Add tests for list infinite scrolling get list ui

force-app/main/default/lwc/toolbarWrapper/__tests__/toolbarWrapper.test.js
Added test for `c/toolbarWrapper` based on test pattern in `c/paginatedListWrapper`.
=> added tests for c/toolbarWrapper

force-app/main/default/lwc/viewVfLwcSource/__tests__/viewVfLwcSource.tests.js, force-app/main/default/lwc/viewVfLwcSource/viewVfLwcSource.html
Adds tests for the `viewVfLwcSource` components
none
=> feat: add test for viewVfLwcSource

force-app/main/default/lwc/viewRecordWithParentRecordData/__tests__/data/getRecord.json, force-app/main/default/lwc/viewRecordWithParentRecordData/__tests__/viewRecordWithParentRecordData.test.js, force-app/main/default/lwc/viewRecordWithParentRecordData/viewRecordWithParentRecordData.js, force-app/test/jest-mocks/schema.js
Adds tests for the`viewRecordWithParentRecordData` component
none
=> feat: add test for viewRecordWithParentRecordData

force-app/main/default/lwc/editableList/__tests__/data/getAccounts.json, force-app/main/default/lwc/editableList/__tests__/editableList.test.js
Adds tests for editableList
editableList didn't have tests
editableList has tests
=> Tests for editableList

force-app/main/default/lwc/createMixedRecordsApex/__tests__/createMixedRecordsApex.test.js, force-app/main/default/lwc/createMixedRecordsApex/createMixedRecordsApex.html, force-app/main/default/lwc/createMixedRecordsApex/createMixedRecordsApex.js
Adds tests for createMixedRecordsApex
createMixedRecordsApex didn't have tests
createMixedRecordsApex has tests
=> Tests for createMixedRecordsApex

force-app/main/default/lwc/viewRecord/__tests__/viewRecord.test.js
Added test for `c/viewRecord component`.
=> Add test for c/viewRecord component

force-app/main/default/lwc/viewRecordWithParentRecordDataWrapper/__tests__/viewRecordWithParentRecordDataWrapper.test.js
Adds tests for the`viewRecordWithParentRecordData` component
none
=> feat: add test for viewRecordWithParentRecordDataWrapper

force-app/main/default/lwc/viewRecordWrapper/__tests__/viewRecordWrapper.test.js
Adds tests for the `viewRecordWrapper` components
none
=> feat: add test for viewRecordWrapper

force-app/main/default/lwc/editRecord/__tests__/editRecord.test.js, force-app/main/default/lwc/editableList/__tests__/editableList.test.js, force-app/main/default/lwc/ldsUtils/__mocks__/ldsUtils.js, force-app/main/default/lwc/listInfiniteScrollingGetListUi/__tests__/listInfiniteScrollingGetListUi.test.js, force-app/main/default/lwc/pageMessagesForm/__tests__/pageMessagesForm.test.js, force-app/main/default/lwc/pageMessagesToast/__tests__/pageMessagesToast.test.js, force-app/main/default/lwc/paginatedList/__tests__/paginatedList.test.js, force-app/main/default/lwc/viewRecordWithParentRecordData/__tests__/viewRecordWithParentRecordData.test.js
=> Fixing a few test scripts

force-app/main/default/lwc/pageBlocks/__tests__/pageBlocks.test.js
Adds tests for the PageBlocks LWC
=> Adds Jest tests for PageBlocks LWC Component

force-app/main/default/lwc/listInfiniteScrolling/__tests__/data/mockGetAccountsPaginatedRecords.json, force-app/main/default/lwc/listInfiniteScrolling/__tests__/listInfiniteScrolling.test.js, force-app/main/default/lwc/listInfiniteScrolling/listInfiniteScrolling.js
List Infinite Scrolling lwc component.
On Behalf of Heather.
=> adds tests for listInfiniteScrolling

force-app/main/default/lwc/pageMessagesDataRetrieval/__tests__/pageMessagesDataRetrieval.test.js, force-app/main/default/lwc/pageMessagesDataRetrieval/pageMessagesDataRetrieval.html
adds jest tests for PageMessageDataRetrieval component
=> PageMessageDataRetrieval Tests

README.md
Aligns trailhead CTA with other sample app READMEs
#
The app had a custom CTA
The app has the CTA aligned with other apps
=> Align trailhead CTA

README.md
Updates unlocked package instructions PS assignment note to be aligned with other sample apps
#
PS assignment note was custom
PS assignment note is aligned with other sample app READMEs
=> Align unlocked package instructions PS assignment note

force-app/main/default/classes/TestListControllerLwc.cls
=> Renamed a var

force-app/main/default/lwc/ldsUtils/ldsUtils.js
Applying change based on [PR](https://github.com/trailheadapps/lwc-recipes/pull/366) from `lwc-recipes`. 
This creates a more simple syntax to ensure error messages that are not in array form are converted to array. 
[X] Tests for the proposed changes have been added/updated.
No changes to functionality, this is purely a code simplification update.
=> simplified syntax to ensure error array

force-app/main/default/classes/TestCreateMixedRecordsApexControllerLwc.cls, force-app/main/default/classes/TestPageMessagesFormController.cls, force-app/main/default/lwc/exampleWrapper/__mocks__/exampleWrapperTemplate.html, force-app/main/default/permissionsets/Visualforce_to_LWC.permissionset-meta.xml
Adds permissions to Permission Set, to adopt @AuraEnabled class permissions critical update
[X] Tests for the proposed changes have been added/updated.
The app PS didn't explicitly give access to @auraenabled methods classes
The app PS does explicitly give access to @auraenabled methods classes
=> @AuraEnabled class permissions critical update

.gitignore, .vscode/extensions.json
This PR adds the recommended VS Code Extension for Code Tours.
none
The Code Tour extension is not set as recommended extension.
The Code Tour extension is now set as recommended extension.
=> feat: add Code Tours as recommended extension

README.md
Add clarification about walkthroughs permission set
https://github.com/trailheadapps/visualforce-to-lwc/issues/91
The note was not clear enough
The note is clearer
=> Add walkthroughs note

README.md
fixes a minor formatting issue in readme.
=> fix: readme markdown formatting

.tours/mixed-records.tour, .tours/record-lists.tour, .tours/single-records.tour, .tours/welcome.tour
#99 
Steps didn't have titles
Steps have titles
=> Add step titles to code tours

bin/install-scratch.bat, bin/install-scratch.sh
Added install scripts for Windows and Unix.
=> Added cross OS install scripts

package-lock.json, package.json
Upgrades deps and includes eslint-config-prettier
[N/A] Code linting and formatting was performed.
=> Upgrade deps and add eslint-config-prettier

package-lock.json, package.json
Upgrade sfdx-lwc-jest to 0.10.4
sfdx-lwc-jest was on version 0.10.2
sfdx-lwc-jest in on version 0.10.4
=> Upgrade sfdx-lwc-jest

sfdx-project.json
Upgrades package version to Spring 21
Package version was Winter 21
Package version is Spring 21
=> Upgrade version name and number in sfdx-project.json

.forceignore
Upgrades forceignore format to v2
Forceignore used format v1
Forceignore uses format v2
=> Upgrade forceignore format

force-app/main/default/lwc/navigateToRecord/navigateToRecord.js
Fix navigation in record list links recipe
#130 
Navigation wasn't working correctly and two tabs ended up open
Navigation works correctly
=> Prevent default navigation on record lists with links recipe

.github/workflows/ci-pr-prerelease.yml, .github/workflows/ci-pr.yml, .github/workflows/ci.yml, .github/workflows/codetour-watch.yml, .github/workflows/packaging-pr-prerelease.yml, .github/workflows/packaging-pr.yml, .github/workflows/packaging.yml, README.md, package-lock.json, package.json
- aligned CI workflows with other sample apps
- skip version checks on Jest
- got rid of GS0 DevHub (using `release=Preview` flag to create pre-release scratch orgs)
=> Updated CI and tooling

.tours/single-records.tour, force-app/main/default/lwc/basicListGetListUi/__tests__/basicListGetListUi.test.js, force-app/main/default/lwc/editableList/__tests__/editableList.test.js, force-app/main/default/lwc/listInfiniteScrolling/__tests__/listInfiniteScrolling.test.js, force-app/main/default/lwc/listInfiniteScrollingGetListUi/__tests__/listInfiniteScrollingGetListUi.test.js, force-app/main/default/lwc/listInfiniteScrollingGetListUiWrapper/listInfiniteScrollingGetListUiWrapper.html, force-app/main/default/lwc/listRecordLinks/__tests__/listRecordLinks.test.js, force-app/main/default/lwc/listWithParentRecordData/__tests__/listWithParentRecordData.test.js, force-app/main/default/lwc/pageMessagesDataRetrieval/__tests__/pageMessagesDataRetrieval.test.js, force-app/main/default/lwc/paginatedList/__tests__/paginatedList.test.js, force-app/main/default/lwc/singleRecords/__tests__/singleRecords.test.js, force-app/main/default/lwc/viewRecordWithParentRecordData/__tests__/viewRecordWithParentRecordData.test.js, package-lock.json, package.json
Removes deprecated wire test functions - See https://github.com/trailheadapps/dreamhouse-lwc/issues/161
https://github.com/trailheadapps/visualforce-to-lwc/issues/161
[X] Tests for the proposed changes have been added/updated.
=> Migrate wire adapter tests to new syntax

force-app/main/default/lwc/datatableWithCustomTypes/__tests__/datatableWithCustomTypes.test.js, force-app/main/default/lwc/datatableWithCustomTypes/datatableWithCustomTypes.js, force-app/main/default/lwc/datatableWithCustomTypes/navigateToRecordTemplate.html, force-app/main/default/lwc/listRecordLinks/__tests__/listRecordLinks.test.js, force-app/main/default/lwc/listRecordLinks/listRecordLinks.js
Improve record links recipe according to PM feedback 
[X] Tests for the proposed changes have been added/updated.
=> Improve record links recipe

.eslintignore, force-app/main/default/applications/Visualforce_to_LWC.app-meta.xml, force-app/main/default/aura/LWCContainerApp/LWCContainerApp.app, force-app/main/default/aura/LWCContainerApp/LWCContainerApp.app-meta.xml, force-app/main/default/flexipages/Interoperability.flexipage-meta.xml, force-app/main/default/lwc/afterRenderHookWrapper/afterRenderHookWrapper.html, force-app/main/default/lwc/beforeRenderHookWrapper/beforeRenderHookWrapper.html, force-app/main/default/lwc/bindingWrapper/bindingWrapper.html, force-app/main/default/lwc/editRecord/__tests__/editRecord.test.js, force-app/main/default/lwc/interoperability/__tests__/interoperability.test.js, force-app/main/default/lwc/interoperability/interoperability.css, force-app/main/default/lwc/interoperability/interoperability.html, force-app/main/default/lwc/interoperability/interoperability.js, force-app/main/default/lwc/interoperability/interoperability.js-meta.xml, force-app/main/default/lwc/singleRecords/singleRecords.html, force-app/main/default/pages/interoperability.page, force-app/main/default/pages/interoperability.page-meta.xml, force-app/main/default/permissionsets/Visualforce_to_LWC.permissionset-meta.xml, force-app/main/default/tabs/Interoperability.tab-meta.xml, package-lock.json, package.json, sfdx-project.json
Adds Interoperability examples
=> Interoperability examples

force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml, force-app/main/default/flexipages/Basics.flexipage-meta.xml, force-app/main/default/flexipages/Error_Handling.flexipage-meta.xml, force-app/main/default/flexipages/Interoperability.flexipage-meta.xml, force-app/main/default/flexipages/Layout.flexipage-meta.xml, force-app/main/default/flexipages/Mixed_Records.flexipage-meta.xml, force-app/main/default/flexipages/Record_Lists.flexipage-meta.xml, force-app/main/default/flexipages/Single_Records.flexipage-meta.xml
Fix flexipage metadata to follow. Winter '22 format.
<flexiPageRegions>
<itemInstances>
<componentInstance>
<componentName>xxxx</componentName>
</componentInstance>
</itemInstances>
<name>content</name>
<type>Region</type>
</flexiPageRegions>
<flexiPageRegions>
<itemInstances>
<componentInstance>
<identifier>xxxxId</identifier>
<componentName>xxxx</componentName>
</componentInstance>
</itemInstances>
<name>content</name>
<type>Region</type>
</flexiPageRegions>
=> Fix flexipage metadata format
